### PR TITLE
Corrected calculation of the current visible elements in the list panel.

### PR DESCRIPTION
**Pull request by dani162**
The change fixes the problem that the last element/elements in the list are not shown because the margin spaces weren't properly calculated in the visibleCells variable.
Removed unnecessary for-loop run-trough.

### CODE REVIEW

**Comment by Juuxel** [comment]
Do you have an example of a screen where the current calculation breaks something? I don't think LibGui's tests cover this currently.

**Comment by dani162** [comment]
TestScreen (CottonClientScreen)
```java
package dani162.testgui.client.gui;

import io.github.cottonmc.cotton.gui.GuiDescription;
import io.github.cottonmc.cotton.gui.client.CottonClientScreen;

public class TestScreen extends CottonClientScreen {
    public TestScreen(GuiDescription description) {
        super(description);
    }
}
```

TestGui (GuiDescription)
```java
package dani162.testgui.client.gui;

import io.github.cottonmc.cotton.gui.client.LightweightGuiDescription;
import io.github.cottonmc.cotton.gui.widget.WListPanel;
import io.github.cottonmc.cotton.gui.widget.WPlainPanel;
import io.github.cottonmc.cotton.gui.widget.data.Insets;

import java.util.ArrayList;
import java.util.List;
import java.util.function.BiConsumer;

public class TestGui extends LightweightGuiDescription {
    private final List<String> dataList;

    public TestGui() {
        dataList = new ArrayList<>();
        for (int i = 0; i < 100; i++) {
            dataList.add("Test list element " + i);
        }

        WPlainPanel root = new WPlainPanel();
        root.setSize(300, 200);
        Insets inset = new Insets(8);
        root.setInsets(inset);

        BiConsumer<String, TestElement> configurator = (String s, TestElement el) -> el.setData(s);

        WListPanel<String, TestElement> list = new WListPanel<>(dataList, TestElement::new, configurator);
        int listWidth = root.getWidth() - inset.left() - inset.right();
        int listHeight = root.getHeight() - inset.top() - inset.bottom();
        root.add(list, 0, 0, listWidth, listHeight);
        list.setListItemHeight(16);

        this.setRootPanel(root);
    }
}
```

TestElement
```java
package dani162.testgui.client.gui;

import io.github.cottonmc.cotton.gui.client.ScreenDrawing;
import io.github.cottonmc.cotton.gui.widget.WLabel;
import io.github.cottonmc.cotton.gui.widget.WPlainPanel;
import net.minecraft.client.util.math.MatrixStack;
import net.minecraft.text.LiteralText;

public class TestElement extends WPlainPanel {
    private String data;
    private WLabel label;

    public TestElement() {
        label = new WLabel(new LiteralText("TestElement"));
        this.add(label, 0, 0);
    }

    public void setData(String data) {
        this.data = data;
        label.setText(new LiteralText(data));
        System.out.println(this.height);
    }

    @Override
    public void paint(MatrixStack matrices, int x, int y, int mouseX, int mouseY) {
        super.paint(matrices, x, y, mouseX, mouseY);
        int color = 0x88_0000FF;
        ScreenDrawing.coloredRect(matrices, x, y + 1, this.width - 1, 1, color);
        ScreenDrawing.coloredRect(matrices, x, y + 1, 1, this.height - 1, color);
        ScreenDrawing.coloredRect(matrices, x, y + this.height - 1, this.width - 1, 1, color);
        ScreenDrawing.coloredRect(matrices, x + this.width - 1, y + 1, 1, this.height - 1, color);
    }
}
```

**Comment by dani162** [comment]
Without fix (should be 99 test elements):
image

With fix:
image

**Review by Juuxel — APPROVED** [review]

**Comment by Juuxel** [comment]
This works perfectly, thanks! Do you mind if I add your test code into the libgui test mod?

**Comment by dani162** [comment]
Yes of course you can add it.

**Pull request merged**
