### PR TITLE
Updated to 1.18.2

### PR DESCRIPTION
**Pull request by Gregory1234**
Updated to 1.18.2 and replaced deprecated ScreenHandler registering API in the test mod.
I didn't bump the mod version.

### CODE REVIEW

**Review by Juuxel — APPROVED** [review]
Thanks, looks perfect!

**Comment by Juuxel** [comment]
I'm not going to make a release from this since it seems there were no actual code changes that would need a 1.18.2 release, but this is good to have for future updates.

**Comment by Gregory1234** [comment]
@Juuxel There were no changes, but there were dependency changes(fabric-structure-api-v1 got removed), so it would be good to make a release, since gradle pulls the outdated version of this dependency which has bad mixins and causes a crash on launch.

**Comment by Gregory1234** [comment]
On that note it might be good to specify which fabric modules are used explicitly to prevent this issue happening in the future.

**Pull request merged**
