### PR TITLE
Add 1.20.2 support

### PR DESCRIPTION
**Pull request by romangraef**

### CODE REVIEW

**Comment by Juuxel** [comment]
Thanks, but there's already extensive work on this, see the `unstable/9.0` branch.

**Comment by romangraef** [comment]
Any ETA on the 9.0 release then?

**Comment by Juuxel** [comment]
Soon™

**Comment by romangraef** [comment]
Does that mean that I am probably better off bundling this myself than waiting on an update? I would like to get to 1.20.2 soon.

**Comment by Juuxel** [comment]
I'll publish the updates as soon as I've finished setting up the new upload process for LibGui.

**Pull request closed without merging**
